issues/urls.py
# pylint: disable-msg=E1120
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

from issues.views import (ProjectListView, ProjectNewView, ProjectSortView,
                          UserListView, UserSortIssueView, ProjectDetailView, IssueDetailView,
                          BurndownChartView, TagCreateView, TagUpdateView, CommitCreateView,
                          NoteCreateView, TagSearchView, sort_issue, new_issue)


urlpatterns = patterns('',
                       url(r'^$', ProjectListView.as_view(), name="project_list"),
                       url(r'^tags/$', TagCreateView.as_view(), name="tag_create_view"),
                       url(r'^tags/(?P<pk>\d+)$', TagUpdateView.as_view(), name="tag_update_view"),
                       url(r'^tags/search$', TagSearchView.as_view(), name="tag_search_view"),
                       url(r'^new_project/$', ProjectNewView.as_view(), name="project_new"),
                       url(r'^project_sort/$', ProjectSortView.as_view(), name="project_sort"),
                       url(r'^profile/(?P<user_id>\d+)$', UserListView.as_view(), name="user_profile_view"),
                       url(r'^profile/(?P<user_id>\d+)/sort$', UserSortIssueView.as_view(), name="user_sort_issue_view"),
                       url(r'^(?P<slug>[\w-]+)/$', ProjectDetailView.as_view(), name="project_detail"),
                       url(r'^(?P<slug>[\w-]+)/filter/(?P<filter>\S+)$', ProjectDetailView.as_view(), name="project_detail"),
                       url(r'^issue/(?P<pk>\d+)$', IssueDetailView.as_view(), name="issue_detail"),
                       url(r'^(?P<slug>[\w-]+)/sort$', sort_issue, name="sort_issue"),
                       url(r'^(?P<slug>[\w-]+)/new$', new_issue, name="new_issue"),
                       url(r'^(?P<slug>[\w-]+)/milestone/(?P<pk>[\w-]+)/chart$', BurndownChartView.as_view(), name="burndown_chart"),
                       url(r'^(?P<pk>\d+)/createcommit/$', CommitCreateView.as_view(), name="commit_create_view"),
                       url(r'^(?P<pk>\d+)/createnote/$', NoteCreateView.as_view(), name="note_create_view"),
                       )

issues/models.py
import datetime
from django.db import models
from django.db.models import Q, Count
from django.utils.timezone import now, utc
from django.contrib.auth.models import User
from django.utils.safestring import SafeString
from issues.helpers import day_range, days_of_work, days_apart, work_left, business_day_range, is_business_day


class Tag(models.Model):
    label = models.CharField(max_length=32)
    color = models.CharField(max_length=6)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.label


class Project(models.Model):

    STATUS_CHOICES = (
        ('AC', 'Active'),
        ('IN', 'Inactive'),
        ('FZ', 'Frozen'),
        ('CP', 'Completed'),
    )

    SCM_CHOICES = (
        ('GH', 'GitHub'),
        ('BB', 'BitBucket'),
    )

    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    status = models.CharField(max_length="64", default='AC', choices=STATUS_CHOICES)
    scm_owner = models.CharField(max_length=64, null=True, blank=True)
    scm_repo = models.CharField(max_length=64, null=True, blank=True)
    scm_type = models.CharField(max_length="64", default='GH', choices=SCM_CHOICES, null=True, blank=True)
    priority = models.IntegerField(default=-1, blank=False, null=False)

    class Meta:
        ordering = ['-priority']

    def __unicode__(self):
        return self.name

    def as_a(self):
        return SafeString('<a href="%s">%s</a>' % (self.get_absolute_url(), self.__unicode__()))

    def open_issues(self):
        return Issue.objects.filter(project=self).exclude(status='DL').exclude(status='NR').exclude(status='CP')

    def get_tags(self):
        # we should filter by project...
        return Tag.objects.all()  # filter(project=self)

    def filtered_issues(self, status_filter):
        return Issue.objects.filter(project=self, status=status_filter)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail', (), {'slug': self.slug})

    def recently_completed_issues(self):
        return self.issue_set.filter(status='CP').order_by('-close_date').exclude(close_date=None)

    def unassigned_issues(self):
        return self.issue_set.filter(status="UA").order_by('-pk')

    def assigned_issues(self):
        return self.issue_set.filter(status="AS")

    def recently_deleted_issues(self):
        return self.issue_set.filter(status="DL").order_by('-close_date')

    def in_progress_issues(self):
        return self.issue_set.filter(status="IP")

    def needs_review_issues(self):
        return self.issue_set.filter(status="NR").order_by('close_date')

    def future_milestones(self):
        return self.milestone_set.filter(deadline__gte=now())

    @property
    def current_milestone(self):
        try:
            return self.future_milestones().annotate(issue_count=Count('issue')).exclude(issue_count=0).order_by('deadline')[0]
        except (Milestone.DoesNotExist, IndexError):
            return None

    def get_scm_url(self):
        if self.scm_owner and self.scm_repo:
            if self.scm_type == 'GH':
                return "https://github.com/" + self.scm_owner + "/" + self.scm_repo
            elif self.scm_type == 'BB':
                return "https://bitbucket.org/" + self.scm_owner + "/" + self.scm_repo
        return None

    def save(self, *args, **kwargs):
        if self.status != "AC":
            self.priority = -1
        super(Project, self).save(*args, **kwargs)


class Issue(models.Model):

    STATUS_CHOICES = (
        ('AS', 'Assigned'),
        ('IP', 'In Progress'),
        ('UA', 'Unassigned'),
        ('CP', 'Completed'),
        ('NR', 'Needs Review'),
        ('DL', 'Deleted'),
    )

    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    priority = models.IntegerField(default=-1, blank=False, null=False)
    user_priority = models.IntegerField(default=-1, blank=False, null=False)
    creator = models.ForeignKey(User, related_name="+")
    assigned_to = models.ForeignKey(User, blank=True, null=True)
    approved_by = models.ForeignKey(User, blank=True, null=True, related_name="issue_approved_by")
    close_date = models.DateTimeField(blank=True, null=True)
    project = models.ForeignKey(Project, null=True)
    days_estimate = models.DecimalField(
        blank=True, null=True, max_digits=65, decimal_places=5, help_text="How many days will it take to complete e.g. 0.5")
    milestone = models.ForeignKey('Milestone', null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    status = models.CharField(max_length="64", blank=True, null=True, choices=STATUS_CHOICES)
    created = models.DateTimeField(default=now)
    viewers = models.ManyToManyField(User, through='IssueViewed', related_name='viewer_set')

    class Meta:
        ordering = ['project', '-priority']

    def save(self, *args, **kwargs):
        try:
            old = Issue.objects.get(pk=self.pk)
            if self.status != "AS":
                self.user_priority = -1
            if self.status == 'DL' and old.status != 'DL':
                self.close_date = now()
                self.priority = -1
                self.assigned_to = None
            elif self.status == 'CP' and old.status != 'CP':
                self.close_date = now()
            elif self.assigned_to is None and old.assigned_to is not None:
                self.status = "UA"
            elif self.assigned_to != old.assigned_to:
                self.status = "AS"

        except Issue.DoesNotExist:
            pass
        super(Issue, self).save(*args, **kwargs)

    def form_class(self):
        from issues.forms import IssueForm
        return IssueForm

    def form_kwargs(self):
        return dict(instance=self, prefix=str(self.pk))

    def form(self, **kwargs):
        form_kwargs = self.form_kwargs()
        form_kwargs.update(kwargs)
        return self.form_class()(**form_kwargs)

    def has_new_notes(self, viewing_user):
        if viewing_user.is_authenticated():
            notes = self.note_set.exclude(creator=viewing_user).order_by('-created')[:1]
            if notes:
                return IssueViewed.objects.filter(user=viewing_user, issue=self).exclude(last_viewed__lte=notes[0].created).count() == 0
        return False

    def get_notes(self):
        return self.note_set.all().order_by('created')

    @models.permalink
    def get_absolute_url(self):
        return ('issue_detail', (), {'pk': self.id})

    def __unicode__(self):
        return self.title


class Commit(models.Model):
    revision = models.CharField(max_length=40)
    issue = models.ForeignKey(Issue)
    created = models.DateTimeField(default=now)

    def get_url(self):
        if self.issue.project.scm_owner and self.issue.project.scm_repo:
            if self.issue.project.scm_type == 'GH':
                return "https://github.com/" + self.issue.project.scm_owner + "/" + self.issue.project.scm_repo + "/commit/" + self.revision
            elif self.issue.project.scm_type == 'BB':
                return "https://bitbucket.org/" + self.issue.project.scm_owner + "/" + self.issue.project.scm_repo + "/commits/" + self.revision
        return None

    def __unicode__(self):
        return self.revision


class UserMethods(User):

    def assigned_issues(self):
        return self.issue_set.filter(status='AS').order_by('-user_priority')

    def inprogress_issues(self):
        return self.issue_set.filter(status='IP')

    def completed_issues(self):
        return self.issue_set.filter(status='CP').order_by('-close_date')

    def last_completed(self):
        completed = self.issue_set.filter(status='CP').order_by('-close_date')
        if (completed.count() > 0):
            return completed[0]
        else:
            return None

    def needs_review_issues(self):
        return self.issue_set.filter(status='NR')

    def all_milestones(self):
        return Milestone.objects.filter(deadline__gte=now(), project__in=self.issue_set.values_list('project', flat=True)).order_by('project')

    class Meta:
        proxy = True


class Milestone(models.Model):
    project = models.ForeignKey(Project)
    deadline = models.DateField(default=now)

    @models.permalink
    def get_chart_url(self):
        return ('burndown_chart', (), {'slug': self.project.slug, 'pk': self.pk})

    def __unicode__(self):
        return str(self.deadline)

    def calculate_burndown_chart(self, width=800, height=450, when=None):
        data = {}
        issues = self.issue_set.all()
        one_day = datetime.timedelta(days=1)
        if when is None:
            when = datetime.datetime.now()
        try:
            start_date = issues.filter(close_date__isnull=False).order_by('close_date')[0].close_date - one_day
        except IndexError:
            start_date = when

        end_date = datetime.datetime.combine(self.deadline, datetime.time(17))
        w = max(len(list(day_range(start_date, end_date))) - 1, 1)
        h = max(days_of_work(issues), 1)
        grid_w = width / w
        grid_h = height / h
        today_width = days_apart(start_date, when)
        start_height = work_left(issues, start_date - one_day)
        points = []
        for date, day in day_range(start_date, min(end_date, when)):
            point = (day, work_left(issues, date))
            points.append(point)
        # optimal "green" line
        try:
            optimal_slope = h / float(len(list(business_day_range(start_date + one_day, end_date))))
        except ZeroDivisionError:
            optimal_slope = 1.0
        optimal_line_points = []
        current_y = 0
        optimal_line_points.append((0, 0))
        for date, day in day_range(start_date + one_day, end_date):
            if is_business_day(date):
                current_y += optimal_slope
            point = (day + 1, current_y)
            optimal_line_points.append(point)

issues/templates/issues/base.html
{% load url from future %}
{% load gravatar %}
<!DOCTYPE html>
<html>
    {% block head %}
      <head>
          <title>{% block title %}YOU FORGOT TO OVERWRITE THE TITLE BLOCK!{% endblock %}</title>
          {% block css %}
              <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/base.css" />
              <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery-ui.css" />
          {% endblock %}
          
          {% block js %}
              <script type="text/javascript" src="{{ STATIC_URL }}js/libs/jquery.tools.min.js"></script>
              <script type="text/javascript" src="{{ STATIC_URL }}js/libs/jquery-ui-1.8.11.custom.min.js"></script>
              <script type="text/javascript" src="{{ STATIC_URL }}js/base.js"></script>
          {% endblock %}
      </head>
    {% endblock %}
    {% block body %}
      <body>
        <!-- The wonderful background texture can be obtained from: http://subtlepatterns.com/navy/ -->
          <section id="container">
            <header>
				<span class = "right">
                    Logged in as: 
                    {% if user.pk %}
                    <a href="{% url 'user_profile_view' user_id=user.pk %}">{{ user.get_full_name }}</a>
                    <img src= "{{ user.email|gravatar }}" class = "gravatar_medium">
                    {% else %}
                    {{ user }}
                    <img src= "{{ nothing|gravatar }}" class = "gravatar_medium">
                    {% endif %}
                </span>
                <h1><a href="{% url 'project_list' %}">Issues</a></h1>

            </header>

            {% block content %}{% endblock %}
            <div class='clear'></div>
          </section>
      </body>
    {% endblock %}
</html>

issues/templates/issues/burndown.html
{% extends 'issues/base.html' %}

{% block title %}Burndown Chart for {{ end_date }} Milestone{% endblock %}

{% block css %}
  <style type="text/css">
    html, body, svg {
      margin: 0px;
      background-color: transparent;
      width: 100%;
      height: 100%;
    }
  </style>
{% endblock %}

{% block js %}{% endblock %}

{% block body %}
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 {{ svg_width }} {{ svg_height }}" preserveAspectRatio="none">
      {% include 'issues/burndown.svg' %}
    </svg>
  </body>
{% endblock %}

issues/templates/issues/issue_edit.html
    <div class="clear hidden edit_drop" id="issue_input">
        {% with issue.form as form %}
            <form class = "edit_form" id="issue-{{ issue.pk }}-edit" action="{{ issue.get_absolute_url }}" method="post">
                {% csrf_token %}
                <div class = "left new_issue_left">
                    <p >{{ form.title.label_tag }}:{{ form.title }}</p>        
                    <p>{{ form.description.label_tag }}:{{ form.description }}</p>
                </div>
                <div class = "right new_issue_right">
                    <p>{{ form.assigned_to.label_tag }}:{{ form.assigned_to }}</p>
                    <p>{{ form.milestone.label_tag }}:
                    <input type="text" name="{{ issue.id }}-milestone" id="id_{{ issue.id }}-milestone" class="milestone-datepicker" 
                    {% if issue.milestone %}
                        value={{ issue.milestone }}
                    {% endif %}
                    /></p> 
                    <p>{{ form.days_estimate.label_tag }}:{{ form.days_estimate }}</p> 
                    <label class = "left">{{ form.tags.label_tag }}:</label>
                   <div class = "tag_editor clear" data-count="{{ tags.count }}">
                        {% for tag in tags %}
                            {% if tag in issue.tags.all %}
                                {% include 'issues/tag_line.html' with checked='True' %}
                            {% else %}
                                {% include 'issues/tag_line.html' %}
                            {% endif %}
                        {% endfor %}
                        <div class = "clear add_tag_area" style = "display: inline-block">
                            <input type="text" class="new_tag_input"/><button type="button" class = "new_tag right">Add</button>
                        </div>
                    </div>
                </div>
                <div class = "clear" >
                    <input type="submit" value="Save"/>
                    <input class="edit-issue-cancel-button" type="Button" value="Cancel"/>
                    <input id="{{ issue.pk }}-delete" class="issue-delete" type="Button" value="Delete"/>
                </div>
            </form>
        {% endwith %}
    </div>

issues/templates/issues/issue_new.html
<form id="new-issue" action="new" method="post">
    <div class = "new_issue_container">
        {% csrf_token %}
        <div class = "left new_issue_left">
            <p>{{ issue_form.title.label_tag }}:{{ issue_form.title }}</p>        
            <p>{{ issue_form.description.label_tag }}:{{ issue_form.description }}</p>
        </div>
        <div class = "right new_issue_right">
            <p>{{ issue_form.assigned_to.label_tag }}:{{ issue_form.assigned_to }}</p>
            <p>{{ issue_form.milestone.label_tag }}:<input type="text" name="milestone" id="id_milestone" class="milestone-datepicker" /></p> 
            <p>{{ issue_form.days_estimate.label_tag }}:{{ issue_form.days_estimate }}</p>      
            <p>{{ issue_form.tags.label_tag }}:</p>
           <div class = "tag_editor clear" data-count="{{ tags.count }}">            
                {% for tag in tags %}
                        {% include 'issues/tag_line.html' %}
                {% endfor %}
                <div class = "clear add_tag_area" style = "display: inline-block">
                    <input type="text" class="new_tag_input"/><button type="button" class = "new_tag right">Add</button>
                </div>
            </div>

        </div>
        <div class = "clear" >
            <input type="submit" value="Save"/>
            <input id="new-issue-cancel-button" type="Button" value="Cancel"/>
        </div>
    </div>
</form>

issues/templates/issues/project_list.html
{% extends "issues/base.html" %}
{% load url from future %}
{% load gravatar %}

{% block title %}Projects{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project_list.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/tab_lists.css" />
    
    <!-- we need to dry this piece of code out, it is also found in user_profile.html and project_detail.html. Ask Shane -->
    <style>
    {% for tagcss in tags %}
        .tag_{{ tagcss.pk }}
        { background-color: #{{ tagcss.color}} ; }        
    {% endfor %}
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL}}js/urlify.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/project_list.js"></script>
    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <script>
        PROJECT_SORT_URL = '{% url "project_sort" %}';
    </script>
{% endblock %}

{% block content %}
    {{ block.super }}
    {% csrf_token %}

    <section id="projects" class='left'>
        <h3 class="header">Projects</h3>
        <div id="tab-buttons" class="tab-buttons">
            <div id="projects-in-progress" class="project-tab tab in-progress active">In-Progress</div>
            <div id="projects-assigned" class="project-tab tab assigned">Assigned</div>
            <div id="projects-unassigned" class="project-tab tab unassigned">Unassigned</div>
            <div id="projects-needs-review" class="project-tab tab needs-review">Needs Review</div>
            <div id="projects-completed" class="project-tab tab completed">Completed</div>
            <div id="projects-deleted" class="project-tab tab deleted">Deleted</div>
            <div id="projects-projects" class="project-tab tab projects">Manage</div>
        </div>
        <div id="project-issues" class="content-border">
        {% for project in object_list %}
            {% if project.status == "AC" %}
                <div class="project">
                    <img class="collapse_issue node left" src="{{ STATIC_URL}}img/collapse.png" /><h4 class="left">{{ project.as_a }}</h4>
                    <div class="nojump collapse-issue-list clear">
                        {% for issue in project.in_progress_issues|slice:":10" %}
                            <div class="issue project-issue in-progress clear">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                <span class="issue-title slide-title">{{ issue }}</span> 
                                <img src="{{ issue.assigned_to.email|gravatar }}" class="gravatar_small right">
                                <a class="right" href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to.first_name }}</a>
                                <div class="details hidden">
                                    {% include 'issues/includes/tag_display.html' %}
                                    {% include 'issues/includes/issue_view.html' %}
                                </div>
                            </div>
                        {% endfor %}
                        {% for issue in project.assigned_issues|slice:":10" %}
                            <div class="issue project-issue assigned clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                <span class="issue-title slide-title">{{ issue }}</span> 
                                <img src="{{ issue.assigned_to.email|gravatar }}" class="gravatar_small right">
                                <a class="right" href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to.first_name }}</a>
                                <div class="details hidden">
                                    {% include 'issues/includes/tag_display.html' %}
                                    {% include 'issues/includes/issue_view.html' %}
                                </div>
                            </div>
                        {% endfor %}
                        {% for issue in project.needs_review_issues %}
                            <div class="issue project-issue needs-review clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                <span class="issue-title slide-title">{{ issue }}</span>                                 
                                <img src="{{ issue.assigned_to.email|gravatar }}" class="gravatar_small right">
                                <a class="right" href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to.first_name }}</a>
                                <div class="details hidden">
                                    {% include 'issues/includes/tag_display.html' %}
                                    {% include 'issues/includes/issue_view.html' %}
                                </div>
                            </div>
                        {% endfor %}
                        {% for issue in project.unassigned_issues|slice:":10" %}
                            <div class="issue project-issue unassigned hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                <span class="issue-title slide-title">{{ issue }}</span> 
                                <div class="details hidden">
                                    {% include 'issues/includes/tag_display.html' %}
                                    {% include 'issues/includes/issue_view.html' %}
                                </div>
                            </div>
                        {% endfor %}
                        {% for issue in project.recently_completed_issues|slice:":10" %}
                            <div class="issue project-issue completed clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                <span class="issue-title slide-title">{{ issue }}</span> 
                                {% if issue.assigned_to %}
                                <img src="{{ issue.assigned_to.email|gravatar }}" class="gravatar_small right">
                                <a class="right" href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to.first_name }}</a>
                                {% endif %}                            
                                <div class="details hidden">
                                    {% include 'issues/includes/tag_display.html' %}
                                    {% include 'issues/includes/issue_view.html' %}
                                </div>
                            </div>
                        {% endfor %}                        
                        {% for issue in project.recently_deleted_issues|slice:":10" %}
                            <div class="issue project-issue deleted hidden">
                            <span class="issue-id" >{{ issue.pk }}</span>
                            <span class="issue-title slide-title">{{ issue }}</span> 
                            <div class="details hidden">
                                {% include 'issues/includes/tag_display.html' %}
                                {% include 'issues/includes/issue_view.html' %}
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if not forloop.last %}
                    <div class="hr clear"></div>
                {% endif %}
            {% endif %}
        {% endfor %}
        </div>
        <div id="project-sort" class="content-border hidden">
            {% include 'issues/project_new.html' %}
            <div>Reordering the projects below determines the global order on the main page.</div>
            <button type="button" class="right" id="new_project_button">New Project</button>
            <ul id="sortable-projects" class="sortable">
                {% for project in object_list %}
                    {% if project.status == "AC" %}
                        <li class="ui-state-default" id="{{ project.pk }}"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>{{ project }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <div id="other-projects">
                <h4>Other Projects</h4>
                {% for project in object_list %}
                    {% if project.status != "AC" %}
                        <div class="other-project">{{ project.as_a }}<div class="right">{{ project.get_status_display }}</div></div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
    
    <section id="users" class='right'>
        <h3>
            Users
        </h3>
        <div id="tab-buttons" class="tab-buttons">
            <div id="users-in-progress" class="user-tab tab in-progress active">In-Progress</div>
            <div id="users-assigned" class="user-tab tab assigned">Assigned</div>
            <div id="users-needs-review" class="user-tab tab needs-review" style="width: 90px;">Needs Review</div>
            <div id="users-completed" class="user-tab tab completed">Completed</div>
            <!-- <div id="users-reorder" class="user-tab tab reorder">Manage</div> -->
        </div>
        <div id="user-issues" class="content-border">
            {% for user in users %}
                <div class="user">
                    <img class="collapse_issue node left" src="{{ STATIC_URL}}img/collapse.png" />
                    <img src= "{{ user.email|gravatar }}" class="gravatar_small left">&nbsp;
                    <h4 class="left"><a href="{% url 'user_profile_view' user_id=user.pk %}">{{ user.first_name }}</a></h4> 
                    <div class="user-issue-list collapse-issue-list clear">
                        {% for issue in user.inprogress_issues %}
                            <div class="issue user-issue in-progress clear">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                {{ issue }}<div class="right"> {{ issue.project.as_a }}</div>
                            </div>
                        {% endfor %}
                        {% for issue in user.assigned_issues %}
                            <div class="issue user-issue assigned clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                {{ issue }}<div class="right"> {{ issue.project.as_a }}</div>
                            </div>
                        {% endfor %}
                        {% for issue in user.completed_issues|slice:":5" %}
                            <div class="issue user-issue completed clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                {{ issue }}<div class="right"> {{ issue.project.as_a }}</div>
                            </div>
                        {% endfor %}
                        {% for issue in user.needs_review_issues %}
                            <div class="issue user-issue needs-review clear hidden">
                                <span class="issue-id" >{{ issue.pk }}</span>
                                {{ issue }}<div class="right"> {{ issue.project.as_a }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if not forloop.last %}
                    <div class="hr"></div>
                {% endif %}
            {% endfor %}
        </div>
        <!--
        <div id="user-sort" class="content-border hidden">
            <span class="small right"><a href="">New User</a></span>
            <ul id="sortable-users" class="sortable">
                {% for user in users %}
                    <li class="ui-state-default" id="{{ user.pk }}"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>{{ user.first_name }} {{ user.last_name }}</li>
                {% endfor %}
            </ul>
        </div>
        -->
    </section>   
{% endblock %}

issues/templates/issues/project_new.html
{% load url from future %}
<div id="new_project" class="hidden clear">
    <form id="new-project" action="{% url 'project_new' %}" method="post">
        {% csrf_token %}
        <label>Project </label>
        {{ project_form.name.label_tag }}:{{ project_form.name }}
        {{ project_form.slug.label_tag }}:{{ project_form.slug }}
        <div class="hidden">
          {{ project_form.priority.label_tag }}:{{ project_form.priority }}
          {{ project_form.status.label_tag }}:{{ project_form.status }}
        </div>
        <input id="new_project_cancel_button" class="right" type="Button" value="Cancel"/>
        <input type="submit" value="Create" class="right"/>
    </form>
    <div id="form_error" class="hidden"></div>
</div>