issues/urls.py
# pylint: disable-msg=E1120
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

from issues.views import (ProjectListView, ProjectNewView, ProjectSortView,
                          UserListView, UserSortIssueView, ProjectDetailView, IssueDetailView,
                          BurndownChartView, TagCreateView, TagUpdateView, CommitCreateView,
                          NoteCreateView, TagSearchView, sort_issue, new_issue)


urlpatterns = patterns('',
                       url(r'^$', ProjectListView.as_view(), name="project_list"),
                       url(r'^tags/$', TagCreateView.as_view(), name="tag_create_view"),
                       url(r'^tags/(?P<pk>\d+)$', TagUpdateView.as_view(), name="tag_update_view"),
                       url(r'^tags/search$', TagSearchView.as_view(), name="tag_search_view"),
                       url(r'^new_project/$', ProjectNewView.as_view(), name="project_new"),
                       url(r'^project_sort/$', ProjectSortView.as_view(), name="project_sort"),
                       url(r'^profile/(?P<user_id>\d+)$', UserListView.as_view(), name="user_profile_view"),
                       url(r'^profile/(?P<user_id>\d+)/sort$', UserSortIssueView.as_view(), name="user_sort_issue_view"),
                       url(r'^(?P<slug>[\w-]+)/$', ProjectDetailView.as_view(), name="project_detail"),
                       url(r'^(?P<slug>[\w-]+)/filter/(?P<filter>\S+)$', ProjectDetailView.as_view(), name="project_detail"),
                       url(r'^issue/(?P<pk>\d+)$', IssueDetailView.as_view(), name="issue_detail"),
                       url(r'^(?P<slug>[\w-]+)/sort$', sort_issue, name="sort_issue"),
                       url(r'^(?P<slug>[\w-]+)/new$', new_issue, name="new_issue"),
                       url(r'^(?P<slug>[\w-]+)/milestone/(?P<pk>[\w-]+)/chart$', BurndownChartView.as_view(), name="burndown_chart"),
                       url(r'^(?P<pk>\d+)/createcommit/$', CommitCreateView.as_view(), name="commit_create_view"),
                       url(r'^(?P<pk>\d+)/createnote/$', NoteCreateView.as_view(), name="note_create_view"),
                       )

issues/models.py
import datetime
from django.db import models
from django.db.models import Q, Count
from django.utils.timezone import now, utc
from django.contrib.auth.models import User
from django.utils.safestring import SafeString
from issues.helpers import day_range, days_of_work, days_apart, work_left, business_day_range, is_business_day


class Tag(models.Model):
    label = models.CharField(max_length=32)
    color = models.CharField(max_length=6)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.label


class Project(models.Model):

    STATUS_CHOICES = (
        ('AC', 'Active'),
        ('IN', 'Inactive'),
        ('FZ', 'Frozen'),
        ('CP', 'Completed'),
    )

    SCM_CHOICES = (
        ('GH', 'GitHub'),
        ('BB', 'BitBucket'),
    )

    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    status = models.CharField(max_length="64", default='AC', choices=STATUS_CHOICES)
    scm_owner = models.CharField(max_length=64, null=True, blank=True)
    scm_repo = models.CharField(max_length=64, null=True, blank=True)
    scm_type = models.CharField(max_length="64", default='GH', choices=SCM_CHOICES, null=True, blank=True)
    priority = models.IntegerField(default=-1, blank=False, null=False)

    class Meta:
        ordering = ['-priority']

    def __unicode__(self):
        return self.name

    def as_a(self):
        return SafeString('<a href="%s">%s</a>' % (self.get_absolute_url(), self.__unicode__()))

    def open_issues(self):
        return Issue.objects.filter(project=self).exclude(status='DL').exclude(status='NR').exclude(status='CP')

    def get_tags(self):
        # we should filter by project...
        return Tag.objects.all()  # filter(project=self)

    def filtered_issues(self, status_filter):
        return Issue.objects.filter(project=self, status=status_filter)

    @models.permalink
    def get_absolute_url(self):
        return ('project_detail', (), {'slug': self.slug})

    def recently_completed_issues(self):
        return self.issue_set.filter(status='CP').order_by('-close_date').exclude(close_date=None)

    def unassigned_issues(self):
        return self.issue_set.filter(status="UA").order_by('-pk')

    def assigned_issues(self):
        return self.issue_set.filter(status="AS")

    def recently_deleted_issues(self):
        return self.issue_set.filter(status="DL").order_by('-close_date')

    def in_progress_issues(self):
        return self.issue_set.filter(status="IP")

    def needs_review_issues(self):
        return self.issue_set.filter(status="NR").order_by('close_date')

    def future_milestones(self):
        return self.milestone_set.filter(deadline__gte=now())

    @property
    def current_milestone(self):
        try:
            return self.future_milestones().annotate(issue_count=Count('issue')).exclude(issue_count=0).order_by('deadline')[0]
        except (Milestone.DoesNotExist, IndexError):
            return None

    def get_scm_url(self):
        if self.scm_owner and self.scm_repo:
            if self.scm_type == 'GH':
                return "https://github.com/" + self.scm_owner + "/" + self.scm_repo
            elif self.scm_type == 'BB':
                return "https://bitbucket.org/" + self.scm_owner + "/" + self.scm_repo
        return None

    def save(self, *args, **kwargs):
        if self.status != "AC":
            self.priority = -1
        super(Project, self).save(*args, **kwargs)


class Issue(models.Model):

    STATUS_CHOICES = (
        ('AS', 'Assigned'),
        ('IP', 'In Progress'),
        ('UA', 'Unassigned'),
        ('CP', 'Completed'),
        ('NR', 'Needs Review'),
        ('DL', 'Deleted'),
    )

    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    priority = models.IntegerField(default=-1, blank=False, null=False)
    user_priority = models.IntegerField(default=-1, blank=False, null=False)
    creator = models.ForeignKey(User, related_name="+")
    assigned_to = models.ForeignKey(User, blank=True, null=True)
    approved_by = models.ForeignKey(User, blank=True, null=True, related_name="issue_approved_by")
    close_date = models.DateTimeField(blank=True, null=True)
    project = models.ForeignKey(Project, null=True)
    days_estimate = models.DecimalField(
        blank=True, null=True, max_digits=65, decimal_places=5, help_text="How many days will it take to complete e.g. 0.5")
    milestone = models.ForeignKey('Milestone', null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    status = models.CharField(max_length="64", blank=True, null=True, choices=STATUS_CHOICES)
    created = models.DateTimeField(default=now)
    viewers = models.ManyToManyField(User, through='IssueViewed', related_name='viewer_set')

    class Meta:
        ordering = ['project', '-priority']

    def save(self, *args, **kwargs):
        try:
            old = Issue.objects.get(pk=self.pk)
            if self.status != "AS":
                self.user_priority = -1
            if self.status == 'DL' and old.status != 'DL':
                self.close_date = now()
                self.priority = -1
                self.assigned_to = None
            elif self.status == 'CP' and old.status != 'CP':
                self.close_date = now()
            elif self.assigned_to is None and old.assigned_to is not None:
                self.status = "UA"
            elif self.assigned_to != old.assigned_to:
                self.status = "AS"

        except Issue.DoesNotExist:
            pass
        super(Issue, self).save(*args, **kwargs)

    def form_class(self):
        from issues.forms import IssueForm
        return IssueForm

    def form_kwargs(self):
        return dict(instance=self, prefix=str(self.pk))

    def form(self, **kwargs):
        form_kwargs = self.form_kwargs()
        form_kwargs.update(kwargs)
        return self.form_class()(**form_kwargs)

    def has_new_notes(self, viewing_user):
        if viewing_user.is_authenticated():
            notes = self.note_set.exclude(creator=viewing_user).order_by('-created')[:1]
            if notes:
                return IssueViewed.objects.filter(user=viewing_user, issue=self).exclude(last_viewed__lte=notes[0].created).count() == 0
        return False

    def get_notes(self):
        return self.note_set.all().order_by('created')

    @models.permalink
    def get_absolute_url(self):
        return ('issue_detail', (), {'pk': self.id})

    def __unicode__(self):
        return self.title


class Commit(models.Model):
    revision = models.CharField(max_length=40)
    issue = models.ForeignKey(Issue)
    created = models.DateTimeField(default=now)

    def get_url(self):
        if self.issue.project.scm_owner and self.issue.project.scm_repo:
            if self.issue.project.scm_type == 'GH':
                return "https://github.com/" + self.issue.project.scm_owner + "/" + self.issue.project.scm_repo + "/commit/" + self.revision
            elif self.issue.project.scm_type == 'BB':
                return "https://bitbucket.org/" + self.issue.project.scm_owner + "/" + self.issue.project.scm_repo + "/commits/" + self.revision
        return None

    def __unicode__(self):
        return self.revision


class UserMethods(User):

    def assigned_issues(self):
        return self.issue_set.filter(status='AS').order_by('-user_priority')

    def inprogress_issues(self):
        return self.issue_set.filter(status='IP')

    def completed_issues(self):
        return self.issue_set.filter(status='CP').order_by('-close_date')

    def last_completed(self):
        completed = self.issue_set.filter(status='CP').order_by('-close_date')
        if (completed.count() > 0):
            return completed[0]
        else:
            return None

    def needs_review_issues(self):
        return self.issue_set.filter(status='NR')

    def all_milestones(self):
        return Milestone.objects.filter(deadline__gte=now(), project__in=self.issue_set.values_list('project', flat=True)).order_by('project')

    class Meta:
        proxy = True


class Milestone(models.Model):
    project = models.ForeignKey(Project)
    deadline = models.DateField(default=now)

    @models.permalink
    def get_chart_url(self):
        return ('burndown_chart', (), {'slug': self.project.slug, 'pk': self.pk})

    def __unicode__(self):
        return str(self.deadline)

    def calculate_burndown_chart(self, width=800, height=450, when=None):
        data = {}
        issues = self.issue_set.all()
        one_day = datetime.timedelta(days=1)
        if when is None:
            when = datetime.datetime.now()
        try:
            start_date = issues.filter(close_date__isnull=False).order_by('close_date')[0].close_date - one_day
        except IndexError:
            start_date = when

        end_date = datetime.datetime.combine(self.deadline, datetime.time(17))
        w = max(len(list(day_range(start_date, end_date))) - 1, 1)
        h = max(days_of_work(issues), 1)
        grid_w = width / w
        grid_h = height / h
        today_width = days_apart(start_date, when)
        start_height = work_left(issues, start_date - one_day)
        points = []
        for date, day in day_range(start_date, min(end_date, when)):
            point = (day, work_left(issues, date))
            points.append(point)
        # optimal "green" line
        try:
            optimal_slope = h / float(len(list(business_day_range(start_date + one_day, end_date))))
        except ZeroDivisionError:
            optimal_slope = 1.0
        optimal_line_points = []
        current_y = 0
        optimal_line_points.append((0, 0))
        for date, day in day_range(start_date + one_day, end_date):
            if is_business_day(date):
                current_y += optimal_slope
            point = (day + 1, current_y)
            optimal_line_points.append(point)

issues/templates/issues/includes/color_selector.html
<div id="color_selector" class = "clear hidden">
    <div id = "color_palette" class = "clear"></div>
    <label style = "display: inline;">#</label>
    <button id = "color_hex_button" type = "button" class="right" >Apply</button>
    <input id = "color_input" type="text" class="right" maxlength="6"/>
</div>

issues/templates/issues/includes/issue_detail.html
{% load gravatar %}
{% load has_new_notes %}
{% load url from future %}
<span class="project-name right">
    {{ issue.project.as_a }}
</span>
<span class="assigned-to">
  {% if issue.assigned_to %}
    <div style="position: relative; left:0; top:0">
      {% if issue.assigned_to.get_full_name %}
        <a href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to.get_full_name }}</a>
      {% else %}
        <a href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.assigned_to }}</a>
      {% endif %}
      {% if issue.status == 'IP' %}
        <img id="gravatar-{{ issue.pk }}" src="{{ STATIC_URL }}img/clock.gif" width=32 height=32 style="background: url({{ issue.assigned_to.email|gravatar }})"/> 
      {% else %}
        <img id="gravatar-{{ issue.pk }}" src="{{ STATIC_URL }}img/spacer.gif" width=32 height=32 style="background: url({{ issue.assigned_to.email|gravatar }})"/>
      {% endif %}
    </div>
  {% else %}
    &nbsp;
  {% endif %}
</span>
<img class="handle" src="{{ STATIC_URL }}img/handle.png" />

<span class="issue-id" >{{ issue.pk }}</span>
{% if issue|has_new_notes:user %}
    <label id="new-notes-{{ issue.pk }}" class="new-note">New Note! </label>
{% endif %}

<span class="issue-title" title="{{ issue.description }}" rel="#issue-details-{{ issue.pk }}">{{ issue }}</span>

{% include 'issues/includes/tag_display.html' %}
{% if issue.milestone %}
  <a class="milestone" href="{{ issue.milestone.get_chart_url }}">{{ issue.milestone }}</a>
{% endif %}

issues/templates/issues/includes/issue_edit.html
    <div class="clear hidden edit_drop" id="issue_input">
        {% with issue.form as form %}
            <form class = "edit_form" id="issue-{{ issue.pk }}-edit" action="{{ issue.get_absolute_url }}" method="post">
                {% csrf_token %}
                <div class = "left new_issue_left">
                    <p >{{ form.title.label_tag }}:{{ form.title }}</p>        
                    <p>{{ form.description.label_tag }}:{{ form.description }}</p>
                    <p> <div class = "tag_form">
                            {{ form.tags.label_tag }}
                            <div id="tag-list-{{ issue.pk }}" class="tag_parent">
                            {% for tag in issue.tags.all %}
                                {% include 'issues/includes/tag_addin.html' %}
                            {% endfor %}
                            </div>
                        </div>
                        <input class = "tag_field" data-pk="{{ issue.pk }}" type="text"/>
                    </p>
                </div>
                <div class = "right new_issue_right">
                    <p>{{ form.assigned_to.label_tag }}:{{ form.assigned_to }}</p>
                    <p>{{ form.milestone.label_tag }}:
                    <input type="text" name="{{ issue.id }}-milestone" id="id_{{ issue.id }}-milestone" class="milestone-datepicker" 
                    {% if issue.milestone %}
                        value={{ issue.milestone }}
                    {% endif %}
                    data-project-pk="{{ issue.project.pk }}"
                    
                    /></p> 
                    <p>{{ form.days_estimate.label_tag }}:{{ form.days_estimate }}</p> 
                </div>
                <div class = "clear" >
                    <input type="submit" value="Save"/>
                    <input class="edit-issue-cancel-button" type="Button" value="Cancel"/>
                    <input id="{{ issue.pk }}-delete" class="issue-delete" type="Button" value="Delete"/>
                </div>
            </form>
        {% endwith %}
    </div>

issues/templates/issues/includes/issue_new.html
 <form id="new-issue" action="new" method="post">
    <div class = "new_issue_container">
        {% csrf_token %}
        <div class = "left new_issue_left">
            <p>{{ issue_form.title.label_tag }}:{{ issue_form.title }}</p>        
            <p>{{ issue_form.description.label_tag }}:{{ issue_form.description }}</p>
            <p> <div class = "tag_form">
                    {{ issue_form.tags.label_tag }}
                    <div id="tag-list-" class="tag_parent"></div>
                </div>
                <input class = "tag_field" data-pk="{{ issue.pk }}" type="text"/>
            </p>

        </div>

        <div class = "right new_issue_right">
            <p>{{ issue_form.assigned_to.label_tag }}:{{ issue_form.assigned_to }}</p>
            <p>{{ issue_form.milestone.label_tag }}:<input type="text" name="milestone" id="id_milestone" class="milestone-datepicker" data-project-pk="{{ project.pk }}"/></p> 
            <p>{{ issue_form.days_estimate.label_tag }}:{{ issue_form.days_estimate }}</p>      
        </div>
        <div class = "clear" >
            <input type="submit" value="Save"/>
            <input id="new-issue-cancel-button" type="Button" value="Cancel"/>
        </div>
    </div>
</form>

issues/templates/issues/includes/issue_view.html
{% load url from future %}
{% load assigned_css_class %}
<div class="hidden clear details_drop" id="issue-details-{{ issue.pk }}" data-note-url="{% url 'note_create_view' issue.pk %}" data-commit-url="{% url 'commit_create_view' issue.pk %}" data-issue-url="{% url 'issue_detail' issue.pk %}"> 

<span class="buttons right">
    <button id="add-commit-{{ issue.pk }}" class="issue-button issue_add_commit">Add Commit</button>  
    <button id="add-note-{{ issue.pk }}" class="issue-button issue_add_note">Add Note</button> 

    {% if issue.status != 'NR' %}
        <button id="{{ issue.pk }}-work-on" class="issue-button issue_work_on">Work On</button>    
        <button id="close-{{ issue.pk }}" class="issue-button issue_complete">Complete</button>                   
    {% else %}
        <button id="{{ issue.pk }}-approve" class="issue-button issue_approve">Approve</button>
        <button id="{{ issue.pk }}-reject" class="issue-button issue_reject">Reject</button>  
    {% endif %}

    
    {% if issue.status != 'DL' and issue.status != 'CP' and issue.status != 'NR' %}
        <button class ="issue-button issue_edit" href="">Edit</button>    
    {% endif %}
</span>

<span class="created-info">
    <p class ="left issue_status issue_creator">Created by: <span class="emphasis">{{ issue.creator.get_full_name }}</span></p> 
    {% if issue.milestone %}
        <p class ="left issue_status issue_dates">Milestone: <span class="emphasis">{{ issue.milestone }}</span></p>
    {% endif %}
    {% if issue.days_estimate %}
        <p class ="left issue_status issue_dates">Days Estimate: <span class="emphasis">{{ issue.days_estimate }}</span></p>
    {% endif %}
</span>

{% with commits=issue.commit_set.all notes=issue.get_notes %}

    
    <div class ="clear issue_description">
        {% if issue.description %}
            <div>
                <span class="field-header">Description</span><br />
                {{ issue.description|linebreaksbr }}
            </div>
        {% else %}                
            No Description Available
        {% endif %}

        <div id="note-list-{{ issue.pk }}" class="note-list">
            <span id="note-header-{{ issue.pk }}" class="field-header {% if not notes %} hidden {% endif %}">Notes</span><br />
            {% for note in notes %}
                <div class="note">{{ note.creator.get_full_name }} on {{ note.created|date:"SHORT_DATETIME_FORMAT" }} </br>&emsp; {{ note|linebreaksbr }}</div>
            {% endfor %}
        </div>
    
        <div>
        <span id="commit-header-{{ issue.pk }}" class="field-header {% if not commits %} hidden {% endif %}">Commits</span><br />
        <ul id = "commit-list-{{ issue.pk }}">
            {% for commit in commits %}
                {% if commit.get_url %}
                 <li><a href="{{ commit.get_url }}" target="_blank">{{ commit }}</a> &emsp; on {{ commit.created|date:"SHORT_DATETIME_FORMAT" }}</li>
                {% else %}
                    <li>{{ commit }}</li>
                {% endif %}
            {% endfor %}
            </ul>
        </div>

        
    </div>

{% endwith %}    

{% if issue.status = 'CP' %}
<div class="">
    <p class ="clear issue_description">
    {% if issue.approved_by %}
         Reviewed by: 
         <span class="emphasis"><a href="{% url 'user_profile_view' user_id=issue.assigned_to.pk %}">{{ issue.approved_by.get_full_name }}</a></span>
         On: 
         <span class="emphasis">{{ issue.close_date }}</span>
     {% else %}
        This issue was not reviewed by anyone.
     {% endif %}
    </p> 
</div>
{% endif %}

</div>

issues/templates/issues/includes/tag_addin.html
{% load url from future %}
<span id="tag-data-{{ issue.pk }}-{{ tag.label|lower }}" {% if tag %} data-tag-update-url="{% url 'tag_update_view' tag.pk %}" {% endif %} data-pk="{{ tag.pk }}" class="left tag_mod tag tag_{{ tag.pk }}"> 
    {{ tag }} 
    <div class = "tag_remove"></div>
</span>

issues/templates/issues/includes/tag_display.html
<div class = "tag_list">
  {% for tag in issue.tags.all %}
    <span class="left tag tag_{{ tag.pk }}"> 
        {{ tag }}        
    </span>
  {% endfor %}
</div>

issues/templates/issues/includes/tag_line.html
{% load url from future %}
<div id = "tag-container-{{ tag.pk }}" class = "tag_line" {% if tag %} data-tag-update-url="{% url 'tag_update_view' tag.pk %}" {% endif %}>
    <div class = "tag_mod tag_{{ tag.pk }}" data-cls="{{ tag.pk }}"></div>&nbsp;
    <label class="tag_label">{{ tag }}</label>
    <input class = "right tag_check" type="checkbox" id="tagchk_{{ tag.pk }}" {% if checked %} checked="" {% endif %}>
</div>